/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 26-Nov-2019 09:10:55
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 5
 * Denominator Length  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\Program Files\MATLAB\R2018a\extern\include\tmwtypes.h 
 */
const int NL = 5;
const real64_T NUM[5] = {
     0.0102094807912,  0.04083792316481,  0.06125688474722,  0.04083792316481,
     0.0102094807912
};
const int DL = 5;
const real64_T DEN[5] = {
                   1,   -1.968427786939,    1.735860709209,  -0.7244708295074,
     0.1203895998962
};
